#!/bin/bash

export ELEPHANT_SERVER_HOST="${ELEPHANT_SERVER_HOST:-0.0.0.0}"
export ELEPHANT_SERVER_MODULES="${ELEPHANT_SERVER_MODULES:-import norse; import torch; import numpy as np}"
export ELEPHANT_SERVER_PORT="${ELEPHANT_SERVER_PORT:-52428}"
# export ELEPHANT_SERVER_DISABLE_RESTRICTION="${ELEPHANT_SERVER_DISABLE_RESTRICTION:-1}"
export ELEPHANT_SERVER_STDOUT="${ELEPHANT_SERVER_STDOUT:-1}"

exec elephant-server start
