#!/bin/bash

DAEMON="${ELEPHANT_SERVER_DAEMON:-0}"
HOST="${ELEPHANT_SERVER_HOST:-127.0.0.1}"
PORT="${ELEPHANT_SERVER_PORT:-52428}"
STDOUT="${ELEPHANT_SERVER_STDOUT:-0}"

usage() {
  echo "Elephant Server"
  echo "---------------"
  echo "Usage: elephant-server log|status|start|stop|restart [-d] [-h <HOST>] [-o] [-p <PORT>]"
  echo ""
  echo "Commands:"
  echo "  log         display the server output log"
  echo "  status      display the status of all server instances"
  echo "  start       start a server instance on <HOST>:<PORT>"
  echo "  stop        stop a server instance on <HOST>:<PORT>"
  echo "  restart     restart (i.e. stop and start) a server instance on <HOST>:<PORT>"
  echo
  echo "Options:"
  echo "  -d                 daemonize the server process"
  echo "  -h <HOST>          use hostname/IP address <HOST> for the server [default: 127.0.0.1]"
  echo "  -o                 print Elephant outputs to the console"
  echo "  -p <PORT>          use port <PORT> for opening the socket [default: 52428]"
}

log() {
  # Follow info logs.
  tail -f "/tmp/elephant-server.log"
}

pid() {
  # Get process ID of instance on defined host and port.
  pgrep -f "gunicorn elephant-server.app --bind ${HOST}:${PORT}"
}

set-gunicorn_opts() {
  # Set opts for gunicorn.
  GUNICORN_OPTS="--bind ${HOST}:${PORT}"
  if [ "${DAEMON}" -eq 1 ]; then
    GUNICORN_OPTS="${GUNICORN_OPTS} --daemon"
  else
    if [ "${STDOUT}" -eq 1 ]; then
      GUNICORN_OPTS="${GUNICORN_OPTS} --log-level debug"
    else
      GUNICORN_OPTS="${GUNICORN_OPTS} --capture-output"
      GUNICORN_OPTS="${GUNICORN_OPTS} --log-file /tmp/elephant-server.log"
    fi
  fi
}

start() {
  # Start server instance.
  if pid > /dev/null;  then
    echo "Elephant Server is already running at http://${HOST}:${PORT}."
  else
    echo "Elephant Server is now running at http://${HOST}:${PORT}."
    if [ "${DAEMON}" -eq 0 ]; then
      echo "Use CTRL + C to stop this service."
      if [ "${STDOUT}" -eq 1 ]; then
        echo "--------------------------------------------------------"
      fi
    fi

    set-gunicorn_opts
    gunicorn ${GUNICORN_OPTS} elephant_server:app
  fi
}

status() {
  # List all processes of Elephant Server.
  PS_AUX="$(ps aux | grep "[g]unicorn elephant_server.app")"
  printf "USER\t\t\tPID\t\tHTTP-SOCKET\n"
  echo "${PS_AUX}" | head -n 1 | awk '{ for(i=1;i<=NF;i++) {if ( i == 1 || i == 2 || i == 15 ) printf $i"\t\t"}; printf "\n" }'
}

stop() {
  # Stop server instance.
  if pid > /dev/null; then
    kill "$(pid 2>&1 | head -n 1)"
    echo "Elephant Server running at http://${HOST}:${PORT} has stopped."
  else
    echo "Elephant Server is not running at http://${HOST}:${PORT}."
    false
  fi
}

CMD=$1; shift
while getopts "dh:op:" opt; do
    case $opt in
        d) DAEMON=1 ;;
        h) HOST=$OPTARG ;;
        o) STDOUT=1 ;;
        p) PORT=$OPTARG ;;
    esac
done

case "$CMD" in
  log) log ;;
  pid) pid ;;
  restart) stop; sleep .5; start ;;
  start)   start ;;
  status)  status ;;
  stop)    stop ;;
  *) usage ;;
esac
